name: Deploy 🌩

on:
  push:
    branches:
      - master
    paths:
      - 'VERSION'

jobs:
  deploy:
    name: Deploy 📦
    runs-on: ubuntu-latest
    steps:
      - name: connect/deploy
        uses: appleboy/ssh-action@dce9d565de8d876c11d93fa4fe677c0285a66d78
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: bash /simurgh/config/deploy.sh
